modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "languagereload"
version = "${version}"
displayName = "Language Reload - Forge"
displayURL="https://github.com/TexTrueStudio/LanguageReload" #optional
logoFile="icon.png" #optional
credits="Jerozgen" #optional
authors="TexTrue, TexTrueStudio, BocchiKessokuTeam" #optional
description = '''
Reduces load times and adds fallbacks for languages.
'''

[[dependencies.languagereload]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.languagereload]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2]"
ordering = "NONE"
side = "BOTH"
